from modules.Classes import user

User1 = user("vlad1.96", "qwerty12", 0)
User1.login(input(), input())
User1.login(input(), input())
User1.login(input(), input())
User1.login(input(), input())
User1.login(input(), input())
User1.login(input(), input())
User1.login(input(), input())
User1.login(input(), input())
User1.login(input(), input())
User1.login(input(), input())
User1.login(input(), input())
User1.login(input(), input())
User1.login(input(), input())
User1.login(input(), input())
User1.login(input(), input())
User1.login(input(), input())